modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="zelda_avetures"
version="1.0.0"
displayName="zelda avetures"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="tmira, MCreator"

[[dependencies.zelda_avetures]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




